/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as VenteRouteImport } from './routes/vente'
import { Route as TransfertsRouteImport } from './routes/transferts'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as EntreesRouteImport } from './routes/entrees'
import { Route as EmployesRouteImport } from './routes/employes'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComptabiliteRouteImport } from './routes/comptabilite'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceVentesRouteImport } from './routes/workspace.ventes'
import { Route as WorkspaceTransfertsRouteImport } from './routes/workspace.transferts'
import { Route as WorkspaceRapportsRouteImport } from './routes/workspace.rapports'
import { Route as WorkspaceProduitsRouteImport } from './routes/workspace.produits'
import { Route as WorkspaceParametresRouteImport } from './routes/workspace.parametres'
import { Route as WorkspaceFournisseursRouteImport } from './routes/workspace.fournisseurs'
import { Route as WorkspaceEntreesRouteImport } from './routes/workspace.entrees'
import { Route as WorkspaceEmployesRouteImport } from './routes/workspace.employes'
import { Route as WorkspaceDevisRouteImport } from './routes/workspace.devis'
import { Route as WorkspaceDashboardRouteImport } from './routes/workspace.dashboard'
import { Route as WorkspaceComptabiliteRouteImport } from './routes/workspace.comptabilite'
import { Route as WorkspaceClientsRouteImport } from './routes/workspace.clients'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const VenteRoute = VenteRouteImport.update({
  id: '/vente',
  path: '/vente',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfertsRoute = TransfertsRouteImport.update({
  id: '/transferts',
  path: '/transferts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreesRoute = EntreesRouteImport.update({
  id: '/entrees',
  path: '/entrees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployesRoute = EmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptabiliteRoute = ComptabiliteRouteImport.update({
  id: '/comptabilite',
  path: '/comptabilite',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceVentesRoute = WorkspaceVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTransfertsRoute = WorkspaceTransfertsRouteImport.update({
  id: '/transferts',
  path: '/transferts',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceRapportsRoute = WorkspaceRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProduitsRoute = WorkspaceProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceParametresRoute = WorkspaceParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceFournisseursRoute = WorkspaceFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceEntreesRoute = WorkspaceEntreesRouteImport.update({
  id: '/entrees',
  path: '/entrees',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceEmployesRoute = WorkspaceEmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDevisRoute = WorkspaceDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceComptabiliteRoute = WorkspaceComptabiliteRouteImport.update({
  id: '/comptabilite',
  path: '/comptabilite',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceClientsRoute = WorkspaceClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/devis': typeof DevisRoute
  '/employes': typeof EmployesRoute
  '/entrees': typeof EntreesRoute
  '/fournisseurs': typeof FournisseursRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transferts': typeof TransfertsRoute
  '/vente': typeof VenteRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/clients': typeof WorkspaceClientsRoute
  '/workspace/comptabilite': typeof WorkspaceComptabiliteRoute
  '/workspace/dashboard': typeof WorkspaceDashboardRoute
  '/workspace/devis': typeof WorkspaceDevisRoute
  '/workspace/employes': typeof WorkspaceEmployesRoute
  '/workspace/entrees': typeof WorkspaceEntreesRoute
  '/workspace/fournisseurs': typeof WorkspaceFournisseursRoute
  '/workspace/parametres': typeof WorkspaceParametresRoute
  '/workspace/produits': typeof WorkspaceProduitsRoute
  '/workspace/rapports': typeof WorkspaceRapportsRoute
  '/workspace/transferts': typeof WorkspaceTransfertsRoute
  '/workspace/ventes': typeof WorkspaceVentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/devis': typeof DevisRoute
  '/employes': typeof EmployesRoute
  '/entrees': typeof EntreesRoute
  '/fournisseurs': typeof FournisseursRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transferts': typeof TransfertsRoute
  '/vente': typeof VenteRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/clients': typeof WorkspaceClientsRoute
  '/workspace/comptabilite': typeof WorkspaceComptabiliteRoute
  '/workspace/dashboard': typeof WorkspaceDashboardRoute
  '/workspace/devis': typeof WorkspaceDevisRoute
  '/workspace/employes': typeof WorkspaceEmployesRoute
  '/workspace/entrees': typeof WorkspaceEntreesRoute
  '/workspace/fournisseurs': typeof WorkspaceFournisseursRoute
  '/workspace/parametres': typeof WorkspaceParametresRoute
  '/workspace/produits': typeof WorkspaceProduitsRoute
  '/workspace/rapports': typeof WorkspaceRapportsRoute
  '/workspace/transferts': typeof WorkspaceTransfertsRoute
  '/workspace/ventes': typeof WorkspaceVentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/devis': typeof DevisRoute
  '/employes': typeof EmployesRoute
  '/entrees': typeof EntreesRoute
  '/fournisseurs': typeof FournisseursRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transferts': typeof TransfertsRoute
  '/vente': typeof VenteRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/clients': typeof WorkspaceClientsRoute
  '/workspace/comptabilite': typeof WorkspaceComptabiliteRoute
  '/workspace/dashboard': typeof WorkspaceDashboardRoute
  '/workspace/devis': typeof WorkspaceDevisRoute
  '/workspace/employes': typeof WorkspaceEmployesRoute
  '/workspace/entrees': typeof WorkspaceEntreesRoute
  '/workspace/fournisseurs': typeof WorkspaceFournisseursRoute
  '/workspace/parametres': typeof WorkspaceParametresRoute
  '/workspace/produits': typeof WorkspaceProduitsRoute
  '/workspace/rapports': typeof WorkspaceRapportsRoute
  '/workspace/transferts': typeof WorkspaceTransfertsRoute
  '/workspace/ventes': typeof WorkspaceVentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/clients'
    | '/comptabilite'
    | '/dashboard'
    | '/demo'
    | '/devis'
    | '/employes'
    | '/entrees'
    | '/fournisseurs'
    | '/onboarding'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/reset-password'
    | '/transferts'
    | '/vente'
    | '/workspace'
    | '/workspace/clients'
    | '/workspace/comptabilite'
    | '/workspace/dashboard'
    | '/workspace/devis'
    | '/workspace/employes'
    | '/workspace/entrees'
    | '/workspace/fournisseurs'
    | '/workspace/parametres'
    | '/workspace/produits'
    | '/workspace/rapports'
    | '/workspace/transferts'
    | '/workspace/ventes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/clients'
    | '/comptabilite'
    | '/dashboard'
    | '/demo'
    | '/devis'
    | '/employes'
    | '/entrees'
    | '/fournisseurs'
    | '/onboarding'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/reset-password'
    | '/transferts'
    | '/vente'
    | '/workspace'
    | '/workspace/clients'
    | '/workspace/comptabilite'
    | '/workspace/dashboard'
    | '/workspace/devis'
    | '/workspace/employes'
    | '/workspace/entrees'
    | '/workspace/fournisseurs'
    | '/workspace/parametres'
    | '/workspace/produits'
    | '/workspace/rapports'
    | '/workspace/transferts'
    | '/workspace/ventes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/clients'
    | '/comptabilite'
    | '/dashboard'
    | '/demo'
    | '/devis'
    | '/employes'
    | '/entrees'
    | '/fournisseurs'
    | '/onboarding'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/reset-password'
    | '/transferts'
    | '/vente'
    | '/workspace'
    | '/workspace/clients'
    | '/workspace/comptabilite'
    | '/workspace/dashboard'
    | '/workspace/devis'
    | '/workspace/employes'
    | '/workspace/entrees'
    | '/workspace/fournisseurs'
    | '/workspace/parametres'
    | '/workspace/produits'
    | '/workspace/rapports'
    | '/workspace/transferts'
    | '/workspace/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  ClientsRoute: typeof ClientsRoute
  ComptabiliteRoute: typeof ComptabiliteRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  DevisRoute: typeof DevisRoute
  EmployesRoute: typeof EmployesRoute
  EntreesRoute: typeof EntreesRoute
  FournisseursRoute: typeof FournisseursRoute
  OnboardingRoute: typeof OnboardingRoute
  ParametresRoute: typeof ParametresRoute
  ProduitsRoute: typeof ProduitsRoute
  RapportsRoute: typeof RapportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TransfertsRoute: typeof TransfertsRoute
  VenteRoute: typeof VenteRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vente': {
      id: '/vente'
      path: '/vente'
      fullPath: '/vente'
      preLoaderRoute: typeof VenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferts': {
      id: '/transferts'
      path: '/transferts'
      fullPath: '/transferts'
      preLoaderRoute: typeof TransfertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrees': {
      id: '/entrees'
      path: '/entrees'
      fullPath: '/entrees'
      preLoaderRoute: typeof EntreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employes': {
      id: '/employes'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof EmployesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptabilite': {
      id: '/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof ComptabiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/ventes': {
      id: '/workspace/ventes'
      path: '/ventes'
      fullPath: '/workspace/ventes'
      preLoaderRoute: typeof WorkspaceVentesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/transferts': {
      id: '/workspace/transferts'
      path: '/transferts'
      fullPath: '/workspace/transferts'
      preLoaderRoute: typeof WorkspaceTransfertsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/rapports': {
      id: '/workspace/rapports'
      path: '/rapports'
      fullPath: '/workspace/rapports'
      preLoaderRoute: typeof WorkspaceRapportsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/produits': {
      id: '/workspace/produits'
      path: '/produits'
      fullPath: '/workspace/produits'
      preLoaderRoute: typeof WorkspaceProduitsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/parametres': {
      id: '/workspace/parametres'
      path: '/parametres'
      fullPath: '/workspace/parametres'
      preLoaderRoute: typeof WorkspaceParametresRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/fournisseurs': {
      id: '/workspace/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/workspace/fournisseurs'
      preLoaderRoute: typeof WorkspaceFournisseursRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/entrees': {
      id: '/workspace/entrees'
      path: '/entrees'
      fullPath: '/workspace/entrees'
      preLoaderRoute: typeof WorkspaceEntreesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/employes': {
      id: '/workspace/employes'
      path: '/employes'
      fullPath: '/workspace/employes'
      preLoaderRoute: typeof WorkspaceEmployesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/devis': {
      id: '/workspace/devis'
      path: '/devis'
      fullPath: '/workspace/devis'
      preLoaderRoute: typeof WorkspaceDevisRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/dashboard': {
      id: '/workspace/dashboard'
      path: '/dashboard'
      fullPath: '/workspace/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/comptabilite': {
      id: '/workspace/comptabilite'
      path: '/comptabilite'
      fullPath: '/workspace/comptabilite'
      preLoaderRoute: typeof WorkspaceComptabiliteRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/clients': {
      id: '/workspace/clients'
      path: '/clients'
      fullPath: '/workspace/clients'
      preLoaderRoute: typeof WorkspaceClientsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceClientsRoute: typeof WorkspaceClientsRoute
  WorkspaceComptabiliteRoute: typeof WorkspaceComptabiliteRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceDevisRoute: typeof WorkspaceDevisRoute
  WorkspaceEmployesRoute: typeof WorkspaceEmployesRoute
  WorkspaceEntreesRoute: typeof WorkspaceEntreesRoute
  WorkspaceFournisseursRoute: typeof WorkspaceFournisseursRoute
  WorkspaceParametresRoute: typeof WorkspaceParametresRoute
  WorkspaceProduitsRoute: typeof WorkspaceProduitsRoute
  WorkspaceRapportsRoute: typeof WorkspaceRapportsRoute
  WorkspaceTransfertsRoute: typeof WorkspaceTransfertsRoute
  WorkspaceVentesRoute: typeof WorkspaceVentesRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceClientsRoute: WorkspaceClientsRoute,
  WorkspaceComptabiliteRoute: WorkspaceComptabiliteRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceDevisRoute: WorkspaceDevisRoute,
  WorkspaceEmployesRoute: WorkspaceEmployesRoute,
  WorkspaceEntreesRoute: WorkspaceEntreesRoute,
  WorkspaceFournisseursRoute: WorkspaceFournisseursRoute,
  WorkspaceParametresRoute: WorkspaceParametresRoute,
  WorkspaceProduitsRoute: WorkspaceProduitsRoute,
  WorkspaceRapportsRoute: WorkspaceRapportsRoute,
  WorkspaceTransfertsRoute: WorkspaceTransfertsRoute,
  WorkspaceVentesRoute: WorkspaceVentesRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  ClientsRoute: ClientsRoute,
  ComptabiliteRoute: ComptabiliteRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  DevisRoute: DevisRoute,
  EmployesRoute: EmployesRoute,
  EntreesRoute: EntreesRoute,
  FournisseursRoute: FournisseursRoute,
  OnboardingRoute: OnboardingRoute,
  ParametresRoute: ParametresRoute,
  ProduitsRoute: ProduitsRoute,
  RapportsRoute: RapportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TransfertsRoute: TransfertsRoute,
  VenteRoute: VenteRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
