/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenteRouteImport } from './routes/vente'
import { Route as TransfertsRouteImport } from './routes/transferts'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as EntreesRouteImport } from './routes/entrees'
import { Route as EmployesRouteImport } from './routes/employes'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComptabiliteRouteImport } from './routes/comptabilite'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceWorkspaceProduitsRouteImport } from './routes/_workspace.workspace.produits'
import { Route as WorkspaceWorkspaceDashboardRouteImport } from './routes/_workspace.workspace.dashboard'

const VenteRoute = VenteRouteImport.update({
  id: '/vente',
  path: '/vente',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfertsRoute = TransfertsRouteImport.update({
  id: '/transferts',
  path: '/transferts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreesRoute = EntreesRouteImport.update({
  id: '/entrees',
  path: '/entrees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployesRoute = EmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptabiliteRoute = ComptabiliteRouteImport.update({
  id: '/comptabilite',
  path: '/comptabilite',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceProduitsRoute =
  WorkspaceWorkspaceProduitsRouteImport.update({
    id: '/workspace/produits',
    path: '/workspace/produits',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceWorkspaceDashboardRoute =
  WorkspaceWorkspaceDashboardRouteImport.update({
    id: '/workspace/dashboard',
    path: '/workspace/dashboard',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/devis': typeof DevisRoute
  '/employes': typeof EmployesRoute
  '/entrees': typeof EntreesRoute
  '/fournisseurs': typeof FournisseursRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transferts': typeof TransfertsRoute
  '/vente': typeof VenteRoute
  '/workspace/dashboard': typeof WorkspaceWorkspaceDashboardRoute
  '/workspace/produits': typeof WorkspaceWorkspaceProduitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/devis': typeof DevisRoute
  '/employes': typeof EmployesRoute
  '/entrees': typeof EntreesRoute
  '/fournisseurs': typeof FournisseursRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transferts': typeof TransfertsRoute
  '/vente': typeof VenteRoute
  '/workspace/dashboard': typeof WorkspaceWorkspaceDashboardRoute
  '/workspace/produits': typeof WorkspaceWorkspaceProduitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/comptabilite': typeof ComptabiliteRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/devis': typeof DevisRoute
  '/employes': typeof EmployesRoute
  '/entrees': typeof EntreesRoute
  '/fournisseurs': typeof FournisseursRoute
  '/onboarding': typeof OnboardingRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transferts': typeof TransfertsRoute
  '/vente': typeof VenteRoute
  '/_workspace/workspace/dashboard': typeof WorkspaceWorkspaceDashboardRoute
  '/_workspace/workspace/produits': typeof WorkspaceWorkspaceProduitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/clients'
    | '/comptabilite'
    | '/dashboard'
    | '/demo'
    | '/devis'
    | '/employes'
    | '/entrees'
    | '/fournisseurs'
    | '/onboarding'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/reset-password'
    | '/transferts'
    | '/vente'
    | '/workspace/dashboard'
    | '/workspace/produits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/clients'
    | '/comptabilite'
    | '/dashboard'
    | '/demo'
    | '/devis'
    | '/employes'
    | '/entrees'
    | '/fournisseurs'
    | '/onboarding'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/reset-password'
    | '/transferts'
    | '/vente'
    | '/workspace/dashboard'
    | '/workspace/produits'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/app'
    | '/auth'
    | '/clients'
    | '/comptabilite'
    | '/dashboard'
    | '/demo'
    | '/devis'
    | '/employes'
    | '/entrees'
    | '/fournisseurs'
    | '/onboarding'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/reset-password'
    | '/transferts'
    | '/vente'
    | '/_workspace/workspace/dashboard'
    | '/_workspace/workspace/produits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  ClientsRoute: typeof ClientsRoute
  ComptabiliteRoute: typeof ComptabiliteRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  DevisRoute: typeof DevisRoute
  EmployesRoute: typeof EmployesRoute
  EntreesRoute: typeof EntreesRoute
  FournisseursRoute: typeof FournisseursRoute
  OnboardingRoute: typeof OnboardingRoute
  ParametresRoute: typeof ParametresRoute
  ProduitsRoute: typeof ProduitsRoute
  RapportsRoute: typeof RapportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TransfertsRoute: typeof TransfertsRoute
  VenteRoute: typeof VenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vente': {
      id: '/vente'
      path: '/vente'
      fullPath: '/vente'
      preLoaderRoute: typeof VenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferts': {
      id: '/transferts'
      path: '/transferts'
      fullPath: '/transferts'
      preLoaderRoute: typeof TransfertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrees': {
      id: '/entrees'
      path: '/entrees'
      fullPath: '/entrees'
      preLoaderRoute: typeof EntreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employes': {
      id: '/employes'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof EmployesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptabilite': {
      id: '/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof ComptabiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/workspace/produits': {
      id: '/_workspace/workspace/produits'
      path: '/workspace/produits'
      fullPath: '/workspace/produits'
      preLoaderRoute: typeof WorkspaceWorkspaceProduitsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspace/dashboard': {
      id: '/_workspace/workspace/dashboard'
      path: '/workspace/dashboard'
      fullPath: '/workspace/dashboard'
      preLoaderRoute: typeof WorkspaceWorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceWorkspaceDashboardRoute: typeof WorkspaceWorkspaceDashboardRoute
  WorkspaceWorkspaceProduitsRoute: typeof WorkspaceWorkspaceProduitsRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceWorkspaceDashboardRoute: WorkspaceWorkspaceDashboardRoute,
  WorkspaceWorkspaceProduitsRoute: WorkspaceWorkspaceProduitsRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  ClientsRoute: ClientsRoute,
  ComptabiliteRoute: ComptabiliteRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  DevisRoute: DevisRoute,
  EmployesRoute: EmployesRoute,
  EntreesRoute: EntreesRoute,
  FournisseursRoute: FournisseursRoute,
  OnboardingRoute: OnboardingRoute,
  ParametresRoute: ParametresRoute,
  ProduitsRoute: ProduitsRoute,
  RapportsRoute: RapportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TransfertsRoute: TransfertsRoute,
  VenteRoute: VenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
